#!/bin/bash -e
# regenerate movabletype mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/etc/movabletype-opensource/mt-config.cgi
    sed -i "s/^$1 \(.*\)/$1 $2/;" $CONF
}

PASSWORD=$(mcookie)
updateconf 'DBPassword' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=movabletype-open --pass="$PASSWORD"

